### ISSUE TITLE
Any plans for displaylink-arch?

### ISSUE THREAD

**Issue by Luc45** [AdnanHodzic/displaylink-debian#421]
Hey buddy,

Any plans for making a `displaylink-arch` version?

Thanks!

**Comment by AdnanHodzic** [comment]
Hey :)

I was thinking about extending it to Red Hat based systems as well as Arch. But since I'm currently [looking for maintainers/developers for this project](https://github.com/AdnanHodzic/displaylink-debian#looking-for-maintainers-developers), I would really prefer if someone else did this. 

It really isn't a lot of work and is pretty straight forward, if you're up for it please give it a try and I'll be more then glad to help you/review code that goes in a PR.

**Comment by Barabazs** [comment]
@Luc45 Can you post the output of: `sudo ./displaylink-debian.sh --debug`
