### ISSUE TITLE
Unsupported platform on linux mint tricia

### ISSUE THREAD

**Issue by khru** [AdnanHodzic/displaylink-debian#464]
![image](https://user-images.githubusercontent.com/6353105/94251021-48964500-ff22-11ea-8c30-cb83d2714a59.png)

The problem is the line `elif [ "$lsb" == "Linuxmint" ];`

**Comment by afabozzi** [comment]
I am having this same issue. Any help appreciated. Thanks.

**Comment by afabozzi** [comment]
Turned out to be a typo in the script. Edit displaylink-debian.sh and on line 196 change the m to uppercase like so:

elif [ "$lsb" == "LinuxMint" ];

After doing that and running the script it worked however my laptop did freeze on the install. I waited a while with no change so I pressed Ctrl+Alt+F5 and logged into terminal and rebooted the machine:

sudo reboot now

After reboot my second screen is now working properly.

THANKS FOR THIS AWESOME SCRIPT GUYS!!!

**Comment by AdnanHodzic** [comment]
@afabozzi please consider [creating a PR](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) to merge these changes with master. Thanks!

**Comment by Barabazs** [comment]
> @afabozzi please consider [creating a PR](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) to merge these changes with master. Thanks!

The script used to check for "LinuxMint" but some users reported that `lsb_release -is` was "Linuxmint". (ie https://github.com/AdnanHodzic/displaylink-debian/issues/448#issuecomment-668785550) The script was modified with this PR https://github.com/AdnanHodzic/displaylink-debian/pull/450

We could do a case insensitive comparison with grep, like this:
```diff
--- elif [ "$lsb" == "Linuxmint" ];
+++ elif echo $lsb | grep -qi "LinuxMint" ;
```

**Comment by AdnanHodzic** [comment]
@Barabazs sounds like good idea to me. As I suggested previously, if someone could make a PR I'll be glad to review and merge with master.
