### ISSUE TITLE
ln: failed to create symbolic link ‘/opt/displaylink/libstdc++.so.6’: No such file or directory

### ISSUE THREAD

**Issue by unit309** [AdnanHodzic/displaylink-debian#51]
This is caused by
```
ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /opt/displaylink/libstdc++.so.6
```
when /opt/displaylink is not exist.

You should probably add
```
mkdir -p /opt/displaylink
```
before.

**Comment by AdnanHodzic** [comment]
Could you please pull the latest changes and try with (re)install? 

In my last commits, I thought it was a good idea to move that symlink creation from "post install" step to configuration part that was done exclusively for Debian and Kali.

But it turns out that at this stage "/opt/displaylink" dir wasn't even created. I just reverted these changes, so you shouldn't have this problem again.

**Comment by AdnanHodzic** [comment]
Pushed additional changes related to libstdc++ symlink, this problem no longer exists.
