### ISSUE TITLE
Unsuported kernel version: 5.19

### ISSUE THREAD

**Issue by varac** [AdnanHodzic/displaylink-debian#745]
I try to reinstall/upgrade but this is what I got:

```
❯ sudo ./displaylink-debian.sh --debug

---------------------------------------------------------------

Unsuported kernel version: 5.19
Please wait for a stable DisplayLink release or try to install the beta
No support will be given for the beta version


This tool is Open Source and feel free to extend it
GitHub repo: https://github.com/AdnanHodzic/displaylink-debian/

---------------------------------------------------------------
```

I'm using PopOS 22.04, which is on the list of supported versions in the README.md.
Does the the upstream driver need an earlier kernel version, or is it this project ?

**Comment by ricklambrechts** [comment]
Same, also for me on debian

**Comment by calebanthony** [comment]
Got this working! I'm also on PopOS 22.04.

The issue I had was needing the newest version of EVDI. Maybe with these steps someone smarter than me can help get this into the repo.

1. Get the official DisplayLink installer here (https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu). I got v5.6.1.
2. Make sure your existing DisplayLink stuff is uninstalled. You should be able to do `displaylink-installer uninstall`.
3. Reboot. This is because EVDI can't be modified while you're in X.
4. Get the newest version of EVDI (I got 1.12.0) from their repo (https://github.com/DisplayLink/evdi/releases). Just download the source code.
5. Move the contents of `evdi-1.12.0/module` to `/usr/src/evdi-1.12.0`.
6. Run `dkms install evdi/1.12.0`. This will install the proper version of EVDI.
7. Run the DisplayLink installer you grabbed in Step 1 and run the `*.run` file. You should see no errors.
8. Reboot and enjoy!

As a side note, I normally have to unplug my dock while booting and plug it back in after boot in order to get things working properly, but now I no longer have to do that. Not sure if that's recent or if I've been doing my superstitious voodoo unnecessarily for a while.

**Comment by godlewski** [comment]
Having the same issue on Ubuntu 22.04.1 LTS

**Comment by varac** [comment]
@calebanthony Thanks for your detailled instructions. I'll rather wait for a proper fix in displaylink-debian though, hoping it will soon land.
